version: "3.1"

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    volumes:
    - .:/code/:consistent
    command: /tmp/web_entrypoint.sh
    ports:
    - 8080:8000
    environment:
      DJANGO_SETTINGS_MODULE: "coursespro.settings"
    links:
      - redis
      
  redis:
    image: redis:6.0.5-alpine
    
  celery:
    restart: always
    build:
      context: .
      dockerfile: api.Dockerfile
    volumes:
      - ./:/code/:consistent
    command: celery worker -A coursespro -l info -E
    environment:
      DJANGO_SETTINGS_MODULE: "coursespro.settings"
    links:
      - redis
